#pragma kernel TestKernel

// data struc which will be sent to VS
struct c2v 
{
	float4 vertex : SV_POSITION;
	float width : TEXCOORD0;
	float4 color : TEXCOORD1;
};


RWStructuredBuffer<c2v> _Vertices;

[numthreads(1,1,1)]
void TestKernel( uint ti : SV_DispatchThreadID )
{
	c2v o;

	o.vertex = float4( ((float)ti/8)-0.5, ((float)ti % 2)/8, 0, 1 );
	o.width = (((float)ti % 3)+1)/90;
	o.color = float4(0,0,1,1);
	
	_Vertices[ ti ] = o;
}